---
- hosts: ubuntunode
  become: yes
  tasks:
  - name: i want to install apache2
    apt:
      name: "{{pavan}}"
      state: present
  - name: start the service
    service:
      name: "{{pavan}}"
      state: started